name: 'ism_video_reel_player'
version: 0.0.1
publish_to: none
homepage: https://github.com/isometrikai/isometrik_video_feeds_flutter.git
environment:
  sdk: '>=3.4.0 <4.0.0'
description: A new Flutter plugin project.

dependencies:
  audioplayers: ^6.5.1
  cached_network_image: ^3.4.1
  cached_video_player_plus: ^4.1.0
  camera: ^0.11.3
  connectivity_plus: ^7.0.0
  device_info_plus: ^12.3.0
  dio: ^5.9.0
  dotted_border: ^3.1.0
  easy_video_editor: ^0.1.3
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_image_compress: ^2.4.0
  flutter_screenutil: ^5.9.3
  flutter_secure_storage: ^9.2.4
  flutter_staggered_grid_view: ^0.7.0
  flutter_svg: ^2.2.3
  flutter_web_plugins:
    sdk: flutter
  fluttertoast: ^9.0.0
  geolocator: ^14.0.2
  get_it: ^9.2.0
  get_thumbnail_video: ^0.7.3
  go_router: ^17.0.0
  google_maps_flutter: ^2.14.0
  googleapis_auth: ^2.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http: ^1.6.0
  image: ^4.7.1
  image_cropper: ^11.0.0
  image_picker: ^1.2.1
  injectable: ^2.7.1+2
  intl: ^0.20.2
  lottie: ^3.3.2
  mime: ^2.0.0
  package_info_plus: ^9.0.0
  percent_indicator: ^4.2.5
  permission_handler: ^12.0.1
  photo_manager: ^3.8.3
  photo_view: ^0.15.0
  plugin_platform_interface: ^2.1.8
  pro_image_editor:
    git:
      url: https://github.com/Navee1998/pro_image_video_editor.git
      ref: stable_custom
  pro_video_editor: ^0.4.0
  pull_to_refresh: ^2.0.0
  reorderables: ^0.6.0
  rudder_sdk_flutter: ^3.3.0
  shared_preferences: ^2.5.3
  shimmer: ^3.0.0
  timeago: ^3.7.1
  url_launcher: ^6.3.2
  uuid: ^4.5.2
  video_compress: ^3.1.4
  video_player: ^2.10.1
  visibility_detector: ^0.4.0+2

dev_dependencies:
  build_runner: ^2.10.4
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1

dependency_overrides:
  analyzer: ^9.0.0
  build: ^4.0.3
  package_info_plus: ^9.0.0

flutter:
  plugin:
    platforms:
      android:
        package: 'com.ism.video_reel.ism_video_reel_player'
        pluginClass: IsmVideoReelPlayerPlugin
      ios:
        pluginClass: IsmVideoReelPlayerPlugin
      linux:
        pluginClass: IsmVideoReelPlayerPlugin
      macos:
        pluginClass: IsmVideoReelPlayerPlugin
      windows:
        pluginClass: IsmVideoReelPlayerPluginCApi
      web:
        pluginClass: IsmVideoReelPlayerWeb
        fileName: 'ism_video_reel_player_web.dart'
  uses-material-design: true
  assets:
    - assets/
    - assets/animation/
    - assets/icons/
    - assets/fonts/
    - assets/loader/
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter/InterVariableFonts.ttf
    - family: Rubik
      fonts:
        - asset: assets/fonts/Rubik/Rubik-Light.ttf
          weight: 300
        - asset: assets/fonts/Rubik/Rubik-Regular.ttf
          weight: 400
        - asset: assets/fonts/Rubik/Rubik-Medium.ttf
          weight: 500
        - asset: assets/fonts/Rubik/Rubik-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Rubik/Rubik-Bold.ttf
          weight: 700
        - asset: assets/fonts/Rubik/Rubik-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Rubik/Rubik-Black.ttf
          weight: 900
    - family: PlayFairDisplay
      fonts:
        - asset: assets/fonts/PlayFair/PlayfairDisplay-Regular.ttf
          weight: 400
        - asset: assets/fonts/PlayFair/PlayfairDisplay-Medium.ttf
          weight: 500
        - asset: assets/fonts/PlayFair/PlayfairDisplay-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/PlayFair/PlayfairDisplay-Bold.ttf
          weight: 700
        - asset: assets/fonts/PlayFair/PlayfairDisplay-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/PlayFair/PlayfairDisplay-Black.ttf
          weight: 900
    - family: Agenda
      fonts:
        - asset: assets/fonts/Agenda/Agenda-Light.ttf
          weight: 300
        - asset: assets/fonts/Agenda/Agenda-Black.ttf
          weight: 900
        - asset: assets/fonts/Agenda/Agenda-Bold.ttf
          weight: 700
    - family: Satoshi
      fonts:
        - asset: assets/fonts/Satoshi/Satoshi-Light.otf
          weight: 300
        - asset: assets/fonts/Satoshi/Satoshi-Regular.otf
          weight: 300
        - asset: assets/fonts/Satoshi/Satoshi-Medium.otf
          weight: 500
        - asset: assets/fonts/Satoshi/Satoshi-Black.otf
          weight: 900
        - asset: assets/fonts/Satoshi/Satoshi-Bold.otf
          weight: 700
