name: 'ism_video_reel_player'
version: 0.0.1
publish_to: none
homepage: https://github.com/isometrikai/isometrik_video_feeds_flutter.git
environment:
  sdk: '>=3.4.0 <4.0.0'
description: A new Flutter plugin project.

dependencies:
  cached_network_image: ^3.4.1
  cached_video_player_plus: ^4.0.4
  connectivity_plus: ^7.0.0
  dotted_border: ^3.1.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_screenutil: ^5.9.3
  flutter_secure_storage: ^9.2.4
  flutter_svg: ^2.2.1
  flutter_web_plugins:
    sdk: flutter
  fluttertoast: ^8.2.12
  get_it: ^8.2.0
  go_router: ^16.2.1
  hive: ^2.2.3
  hive_flutter: ^1.0.0
  http: ^1.5.0
  image: ^4.5.4
  injectable: ^2.5.1
  intl: ^0.20.2
  lottie: ^3.1.0
  package_info_plus: ^9.0.0
  plugin_platform_interface: ^2.1.8
  pull_to_refresh: ^2.0.0
  shared_preferences: ^2.5.3
  url_launcher: ^6.3.2
  video_player: ^2.10.0
  visibility_detector: ^0.4.0+2
  uuid: ^4.3.3

dev_dependencies:
  build_runner: ^2.4.13
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1

flutter:
  plugin:
    platforms:
      android:
        package: 'com.ism.video_reel.ism_video_reel_player'
        pluginClass: IsmVideoReelPlayerPlugin
      ios:
        pluginClass: IsmVideoReelPlayerPlugin
      linux:
        pluginClass: IsmVideoReelPlayerPlugin
      macos:
        pluginClass: IsmVideoReelPlayerPlugin
      windows:
        pluginClass: IsmVideoReelPlayerPluginCApi
      web:
        pluginClass: IsmVideoReelPlayerWeb
        fileName: 'ism_video_reel_player_web.dart'
  uses-material-design: true
  assets:
    - assets/
    - assets/icons/
    - assets/fonts/
    - assets/loader/
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter/InterVariableFonts.ttf
    - family: Rubik
      fonts:
        - asset: assets/fonts/Rubik/Rubik-Light.ttf
          weight: 300
        - asset: assets/fonts/Rubik/Rubik-Regular.ttf
          weight: 400
        - asset: assets/fonts/Rubik/Rubik-Medium.ttf
          weight: 500
        - asset: assets/fonts/Rubik/Rubik-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Rubik/Rubik-Bold.ttf
          weight: 700
        - asset: assets/fonts/Rubik/Rubik-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Rubik/Rubik-Black.ttf
          weight: 900
    - family: PlayFairDisplay
      fonts:
        - asset: assets/fonts/PlayFair/PlayfairDisplay-Regular.ttf
          weight: 400
        - asset: assets/fonts/PlayFair/PlayfairDisplay-Medium.ttf
          weight: 500
        - asset: assets/fonts/PlayFair/PlayfairDisplay-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/PlayFair/PlayfairDisplay-Bold.ttf
          weight: 700
        - asset: assets/fonts/PlayFair/PlayfairDisplay-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/PlayFair/PlayfairDisplay-Black.ttf
          weight: 900
    - family: Agenda
      fonts:
        - asset: assets/fonts/Agenda/Agenda-Light.ttf
          weight: 300
        - asset: assets/fonts/Agenda/Agenda-Black.ttf
          weight: 900
        - asset: assets/fonts/Agenda/Agenda-Bold.ttf
          weight: 700
    - family: Satoshi
      fonts:
        - asset: assets/fonts/Satoshi/Satoshi-Light.otf
          weight: 300
        - asset: assets/fonts/Satoshi/Satoshi-Regular.otf
          weight: 300
        - asset: assets/fonts/Satoshi/Satoshi-Medium.otf
          weight: 500
        - asset: assets/fonts/Satoshi/Satoshi-Black.otf
          weight: 900
        - asset: assets/fonts/Satoshi/Satoshi-Bold.otf
          weight: 700
